env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[41c100127edddb4a71912925d61dafc9b59cd2c9f881f2353fda80d79505386774c256ba7df1ff1d9052239443d17db0]"
    bot_api: "ENCRYPTED[06a546bc2cf505617c93a4cc34213f4474241bf78fe59556b21b40d1ab640d07cbf46e6af564c076a538c973744fb2da]"
    tg_id: "ENCRYPTED[30bb0149dbb9065c24e0053071cf7148fd3575dcecb089cb07324106123fc02826a69407b3be9ef9a878f91804b5e62c]"

task:
    name: haboc
    timeout_in: 120m
    container:
      image: inok2341/builder:latest
      cpu: 8
      memory: 32G

    rclone_setup_script:
      - mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
    download_ccache_background_script:
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Download ccache at $(date)&chat_id=${tg_id}&parse_mode=html"
      - df -h && free -h && nproc && cat /etc/os* && env
      - curl https://ap.apd1.workers.dev/4:/havoc/ccache.tar.gz -o /tmp/ccache.tar.gz
      - cd /tmp
      - time tar xf ccache.tar.gz
      - rm -rf ccache.tar.gz
    sync_script:
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Sync ROM at $(date)&chat_id=${tg_id}&parse_mode=html"
      - git config --global  user.name "rahul9999xda"
      - git config --global  user.email "rahul9999xda@gmail.com"
      - mkdir -p /tmp/rom # Where to sync source
      - cd /tmp/rom
      - repo init --depth=1 --no-repo-verify -u https://github.com/Havoc-OS/android_manifest.git -b eleven -g default,-device,-mips,-darwin,-notdefault
      - git clone https://github.com/pocox3pro/Local-Manifests.git --depth 1 -b havoc .repo/local_manifests
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8
    monitor_background_script:
      - ./monitor
    build_script:
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Build ROM at $(date)&chat_id=${tg_id}&parse_mode=html"
      - ./build
      - time rclone copy /tmp/rom/out/error.log remote:havoc -P
    upload_rom_script:
      - ./uprom
    compress_ccache_script:    
      - ./tarccache
    upload_ccache_script:
      - cd /tmp
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Uploading ccache at $(date)&chat_id=${tg_id}&parse_mode=html"
      - time rclone copy ccache.tar.gz remote:havoc -P
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Upload ccache done at $(date)&chat_id=${tg_id}&parse_mode=html"
