#!/bin/bash

cd /tmp/rom

. build/envsetup.sh
lunch derp_X00T-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z

mka derp -j8 & # dont remove that '&'
sleep 90m
kill %1
ccache -s
