#!/bin/bash

cd /tmp/rom

. build/envsetup.sh
lunch havoc_vayu-user
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
export TZ=Asia/Kolkata #put before last build command
ccache -M 20G
ccache -o compression=true
ccache -z

#mka bacon -j8 & # dont remove that '&'
#sleep 90m
#kill %1
#ccache -s

mka bacon -j8
