#!/bin/bash

ls /tmp/rom/out

cd /tmp

curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Uploading ROM if exist at $(date)&chat_id=${tg_id}&parse_mode=html"

send_zip=$(ls rom/out/target/product/vayu/*.zip)

time rclone copy $send_zip remote:vayuccache -P

dlink=$(basename rom/out/target/product/vayu/*.zip)

curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Download ROM Link https://ap.apd1.workers.dev/4:/vayuccache/$(dlink)&chat_id=${tg_id}&parse_mode=html"
